apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::143694936311:role/demo-prod2021031220181387500000000b"
      "username": "system:node:{{EC2PrivateDNSName}}"
  mapUsers: |
    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::143694936311:user/system/githubactions"
      "username": "githubactions"
    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::143694936311:user/smarconi"
      "username": "smarconi"

